/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include <vector>


//==============================================================================
/**
*/
class EchoplexAudioProcessor  : public AudioProcessor
{
public:
    //==============================================================================
    EchoplexAudioProcessor();
    ~EchoplexAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock (AudioSampleBuffer&, MidiBuffer&) override;

    //==============================================================================
    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==============================================================================
    const String getName() const override;

    const String getInputChannelName (int channelIndex) const override;
    const String getOutputChannelName (int channelIndex) const override;
    bool isInputChannelStereoPair (int index) const override;
    bool isOutputChannelStereoPair (int index) const override;

    bool acceptsMidi() const override;
    bool producesMidi() const override;
    bool silenceInProducesSilenceOut() const override;
    double getTailLengthSeconds() const override;

    //==============================================================================
    int getNumPrograms() override;
    int getCurrentProgram() override;
    void setCurrentProgram (int index) override;
    const String getProgramName (int index) override;
    void changeProgramName (int index, const String& newName) override;

    //==============================================================================
    void getStateInformation (MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;
    
    typedef struct {
        std::vector<float> buffer;
        int current_index=0;
        int length;
    } RingBuffer;
    
    typedef struct {
        double b0, b1, b2, a0, a1, a2;
    } biquadCoeffs;
    
    // Echoplex variables
    double feedback = 0.5;
    float mix = 0;
    float dry_mix = -(0.5 * mix) + 0.5;
    float wet_mix = (0.5 * mix) + 0.5;
    float delay_in_samples = 5000;
    int max_delay_time;
    
    bool disable_write = false;
    
    float filterCutoff = 1000;
    bool filterIsIn = true;
    
    float saturation = 5;
    bool saturation_active = false;
    
    float noiseAmount = 0.015;
    bool noise_in = false;
    
    bool bypass = false;
    bool soundOnSound = false;
    
    // Output variables
    float output_scale_factor = 0.6;

    
    

private:
    //==============================================================================
    
    int mod (int, int);
    
    // Ring buffer operation functions
    RingBuffer *ringbuffer_create (int);
    void ringbuffer_destroy (RingBuffer *);
    
    // Ring buffer declaration
    std::vector<RingBuffer> ringBuf;
    
    float actual_delay;
    float actual_cutoff;
    
    // Counter for interpolation
    int sample_count = 0;
    
    // Filter coefficients
    static const int filterOrder = 126;
    float filter_coeffs[126];
    void calculate_filter_coeffs (float);
    

    // Intepolation function
    float lagrange_interpolate (int, int, int, float);


    
    // Maths functions
    float sinc (float);

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (EchoplexAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
