/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
EchoplexAudioProcessorEditor::EchoplexAudioProcessorEditor (EchoplexAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (630, 350);
    
    // Feedback
    addAndMakeVisible (feedbackSlider);
    feedbackSlider.setSliderStyle (Slider::Rotary);
    feedbackSlider.setRange(0.0, 0.8);
    feedbackSlider.setTextBoxStyle (Slider::NoTextBox, false, 90, 0);
    feedbackSlider.setValue(processor.feedback);
    feedbackSlider.addListener (this);
    
    addAndMakeVisible (feedbackLabel);
    feedbackLabel.setText ("Feedback", dontSendNotification);
    feedbackLabel.attachToComponent (&feedbackSlider, false);
    feedbackLabel.setJustificationType(Justification::centredTop);
    
    // Mix
    addAndMakeVisible (mixSlider);
    mixSlider.setSliderStyle (Slider::Rotary);
    mixSlider.setRange(-1.0, 1.0);
    mixSlider.setTextBoxStyle (Slider::NoTextBox, false, 90, 0);
    mixSlider.setValue(processor.mix);
    mixSlider.addListener (this);
    
    addAndMakeVisible (mixLabel);
    mixLabel.setText ("Mix", dontSendNotification);
    mixLabel.attachToComponent (&mixSlider, false);
    mixLabel.setJustificationType(Justification::centredTop);
    
    // Delay time
    addAndMakeVisible (delaySlider);
    delaySlider.setSliderStyle (Slider::Rotary);
    delaySlider.setRange(0.0, 2000.0);
    delaySlider.setTextBoxStyle (Slider::NoTextBox, false, 90, 0);
    delaySlider.setPopupDisplayEnabled (true, this);
    delaySlider.setTextValueSuffix (" ms");
    delaySlider.setValue((processor.delay_in_samples * 1000) / processor.getSampleRate());  // Convert delay in samples to delay in ms
    delaySlider.addListener (this);
    
    addAndMakeVisible (delayLabel);
    delayLabel.setText ("Delay", dontSendNotification);
    delayLabel.attachToComponent (&delaySlider, false);
    delayLabel.setJustificationType(Justification::centredTop);
    
    // Filter cutoff
    addAndMakeVisible (cutoffSlider);
    cutoffSlider.setSliderStyle (Slider::Rotary);
    cutoffSlider.setRange(10, 15000);
    cutoffSlider.setTextBoxStyle (Slider::NoTextBox, false, 90, 0);
    cutoffSlider.setPopupDisplayEnabled (true, this);
    cutoffSlider.setTextValueSuffix (" Hz");
    cutoffSlider.setSkewFactorFromMidPoint (4000);
    cutoffSlider.setValue(processor.filterCutoff);
    cutoffSlider.addListener (this);
    
    addAndMakeVisible (cutoffLabel);
    cutoffLabel.setText ("Cutoff", dontSendNotification);
    cutoffLabel.attachToComponent (&cutoffSlider, false);
    cutoffLabel.setJustificationType(Justification::centredTop);
    
    // Saturation amount
    addAndMakeVisible (saturationSlider);
    saturationSlider.setSliderStyle (Slider::Rotary);
    saturationSlider.setRange(1, 50);
    saturationSlider.setSkewFactorFromMidPoint (10);
    saturationSlider.setTextBoxStyle (Slider::NoTextBox, false, 90, 0);
    saturationSlider.setValue(processor.saturation);
    saturationSlider.addListener (this);
    
    addAndMakeVisible (saturationLabel);
    saturationLabel.setText ("Saturation", dontSendNotification);
    saturationLabel.attachToComponent (&saturationSlider, false);
    saturationLabel.setJustificationType(Justification::centredTop);
    
    // Noise amount
    addAndMakeVisible (noiseSlider);
    noiseSlider.setSliderStyle (Slider::Rotary);
    noiseSlider.setRange(0, 0.3);
    noiseSlider.setSkewFactorFromMidPoint (0.06);
    noiseSlider.setTextBoxStyle (Slider::NoTextBox, false, 90, 0);
    noiseSlider.setValue(processor.noiseAmount);
    noiseSlider.addListener (this);
    
    addAndMakeVisible (noiseLabel);
    noiseLabel.setText ("Noise", dontSendNotification);
    noiseLabel.attachToComponent (&noiseSlider, false);
    noiseLabel.setJustificationType(Justification::centredTop);
    
    // Bypass Button
    addAndMakeVisible (bypassButton);
    bypassButton.setClickingTogglesState(true);
    bypassButton.addListener (this);
    
    addAndMakeVisible (delayLabel);
    bypassLabel.setText ("Plugin Bypass", dontSendNotification);
    bypassLabel.attachToComponent (&bypassButton, false);
    bypassLabel.setJustificationType(Justification::centredTop);
    
    // Sound on Sound Button
    addAndMakeVisible (SoSButton);
    SoSButton.setClickingTogglesState(true);
    SoSButton.addListener (this);
    
    addAndMakeVisible (SoSLabel);
    SoSLabel.setText ("SoS", dontSendNotification);
    SoSLabel.attachToComponent (&SoSButton, false);
    SoSLabel.setJustificationType(Justification::centredTop);
    
    // Disable Write Button
    addAndMakeVisible (writeButton);
    writeButton.setClickingTogglesState(true);
    writeButton.addListener (this);
    
    addAndMakeVisible (writeLabel);
    writeLabel.setText ("Disable Write", dontSendNotification);
    writeLabel.attachToComponent (&writeButton, false);
    writeLabel.setJustificationType(Justification::centredTop);
    
    // Filter bypass
    addAndMakeVisible (filterButton);
    filterButton.setClickingTogglesState(true);
    filterButton.addListener (this);
    
    addAndMakeVisible (filterLabel);
    filterLabel.setText ("Filter Bypass", dontSendNotification);
    filterLabel.attachToComponent (&filterButton, false);
    filterLabel.setJustificationType(Justification::centredTop);
    
    // Saturation
    addAndMakeVisible (saturationButton);
    saturationButton.setClickingTogglesState(true);
    saturationButton.addListener (this);
    
    addAndMakeVisible (saturationButtonLabel);
    saturationButtonLabel.setText ("Saturation In", dontSendNotification);
    saturationButtonLabel.attachToComponent (&saturationButton, false);
    saturationButtonLabel.setJustificationType(Justification::centredTop);
    
    // Noise Button
    addAndMakeVisible (noiseButton);
    noiseButton.setClickingTogglesState(true);
    noiseButton.addListener (this);
    
    addAndMakeVisible (noiseButtonLabel);
    noiseButtonLabel.setText ("Noise In", dontSendNotification);
    noiseButtonLabel.attachToComponent (&noiseButton, false);
    noiseButtonLabel.setJustificationType(Justification::centredTop);
    
}

EchoplexAudioProcessorEditor::~EchoplexAudioProcessorEditor()
{
}

//==============================================================================
void EchoplexAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::lightgrey);

    g.setColour (Colours::black);
    
    g.setFont (Font ("helveticaNeue", 20.0f, Font::bold));
    g.drawFittedText ("Echoplex", 0, 10, 650, 20, Justification::centredTop, 0);
    
    g.setFont (Font ("helveticaNeue", 15.0f, Font::plain));
    g.drawFittedText ("Robin D'Arcy", 0, 35, 650, 20, Justification::centredTop, 0);
    
    g.setFont (Font ("helveticaNeue", 10.0f, Font::plain));
    g.drawFittedText ("Dry", 120, 160, 50, 20, Justification::topLeft, 0);
    g.drawFittedText ("Wet", 180, 160, 50, 20, Justification::topLeft, 0);
    g.drawFittedText ("Use with SoS for loop", 210, 310, 120, 20, Justification::topLeft, 0);

}

void EchoplexAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
    
    feedbackSlider.setBounds(20, 80, 80, 80);
    mixSlider.setBounds(120, 80, 80, 80);
    delaySlider.setBounds(220, 80, 80, 80);
    cutoffSlider.setBounds(320, 80, 80, 80);
    saturationSlider.setBounds(420, 80, 80, 80);
    noiseSlider.setBounds(520, 80, 80, 80);
    
    bypassButton.setBounds(20, 220, 80, 80);
    SoSButton.setBounds(120, 220, 80, 80);
    writeButton.setBounds(220, 220, 80, 80);
    filterButton.setBounds(320, 220, 80, 80);
    saturationButton.setBounds(420, 220, 80, 80);
    noiseButton.setBounds(520, 220, 80, 80);

}

void EchoplexAudioProcessorEditor::sliderValueChanged (Slider* slider)
{
    if (slider == &feedbackSlider)
    {
        processor.feedback = feedbackSlider.getValue();
    }
    else if (slider == &mixSlider)
    {
        processor.mix = mixSlider.getValue();
        processor.dry_mix = -(0.5 * processor.mix) + 0.5;
        processor.wet_mix = (0.5 * processor.mix) + 0.5;
    }
    else if (slider == &delaySlider)
    {
        // Convert delay in ms to delay in samples
        processor.delay_in_samples = (delaySlider.getValue() / 1000.0) * processor.getSampleRate();
    }
    else if (slider == &cutoffSlider)
    {
        processor.filterCutoff = cutoffSlider.getValue();
    }
    else if (slider == &saturationSlider)
    {
        processor.saturation = saturationSlider.getValue();
    }
    else if (slider == &noiseSlider)
    {
        processor.noiseAmount = noiseSlider.getValue();
    }
    
}

void EchoplexAudioProcessorEditor::buttonClicked (Button *button)
{
    if (button == &bypassButton)
    {
        processor.bypass = ! processor.bypass;
    }
    else if (button == &SoSButton)
    {
        processor.soundOnSound = ! processor.soundOnSound;
    }
    else if (button == &filterButton)
    {
        processor.filterIsIn = ! processor.filterIsIn;
    }
    else if (button == &saturationButton)
    {
        processor.saturation_active = ! processor.saturation_active;
    }
    else if (button == &noiseButton)
    {
        processor.noise_in = ! processor.noise_in;
    }
    else if (button == &writeButton)
    {
        processor.disable_write = ! processor.disable_write;
    }
}

